export const TRIP_EMOJIS = [
  '✈️', '🏖️', '🗺️', '🌴', '🎸', '🏔️', '🌆', '🍜',
  '🎡', '🛳️', '🎭', '🏯', '🌺', '🎪', '🧳', '🗼',
  '🌅', '🏝️', '🎶', '🌍',
]

export const ACTIVITY_EMOJIS = [
  { emoji: '✈️', label: 'Flight' },
  { emoji: '🏨', label: 'Hotel' },
  { emoji: '🍜', label: 'Food' },
  { emoji: '🏛️', label: 'Sightseeing' },
  { emoji: '🎯', label: 'Activity' },
  { emoji: '🛍️', label: 'Shopping' },
  { emoji: '🎵', label: 'Music' },
  { emoji: '🚕', label: 'Transport' },
  { emoji: '🏖️', label: 'Beach' },
  { emoji: '⛩️', label: 'Temple' },
  { emoji: '🍸', label: 'Nightlife' },
  { emoji: '📸', label: 'Photo' },
  { emoji: '💆', label: 'Spa' },
  { emoji: '🚶', label: 'Walk' },
  { emoji: '🎪', label: 'Show' },
  { emoji: '📌', label: 'Other' },
]

export const COUNTRY_FLAGS = {
  'Philippines': '🇵🇭',
  'Singapore': '🇸🇬',
  'Thailand': '🇹🇭',
  'Malaysia': '🇲🇾',
  'Indonesia': '🇮🇩',
  'Vietnam': '🇻🇳',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Taiwan': '🇹🇼',
  'Cambodia': '🇰🇭',
  'Myanmar': '🇲🇲',
  'Laos': '🇱🇦',
  'India': '🇮🇳',
  'China': '🇨🇳',
  'Hong Kong': '🇭🇰',
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'USA': '🇺🇸',
  'UK': '🇬🇧',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Germany': '🇩🇪',
  'Netherlands': '🇳🇱',
  'Greece': '🇬🇷',
  'Turkey': '🇹🇷',
  'UAE': '🇦🇪',
  'Mexico': '🇲🇽',
  'Brazil': '🇧🇷',
  'Canada': '🇨🇦',
}
